name: 'CD'
run-name: >-
  ${{ github.ref_name == 'main' && format('Release stable by @{0}', github.actor) ||
      github.ref_name == 'dev' && format('Release preview by @{0}', github.actor) ||
      format('Release {0} by @{1}', github.ref_name, github.actor) }}
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  cd:
    name: CD
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Project
      uses: ./.github/actions/setup-project
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      id: release
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REF: ${{ github.ref }}
      run: |
        if [[ "$GITHUB_REF" == "refs/heads/main" ]]; then
          npx nx release --skip-publish
          npx nx run-many -t build -t package
          npx nx release publish -g packages
        else
          npx nx release --preid=preview --skip-publish
          npx nx run-many -t build -t package
          npx nx release publish -g packages --tag=preview
        fi


